const announcements = [
  { date: "24 Σεπ 2026", year: 2026, type: "Νέα", title: "Αγιασμός και έναρξη των φθινοπωρινών δράσεων", attachments: ["photo"] },
  { date: "12 Ιουν 2026", year: 2026, type: "Ανακοίνωση", title: "Πρόσκληση για την ετήσια τακτική γενική συνέλευση", attachments: ["pdf"] },
  { date: "08 Μαϊ 2025", year: 2025, type: "Εκδήλωση", title: "Μια μουσική βραδιά αλληλεγγύης στο Άσυλο", attachments: ["photo", "photo"] },
  { date: "15 Δεκ 2024", year: 2024, type: "Νέα", title: "Χριστουγεννιάτικη γιορτή με φίλους και εθελοντές", attachments: ["photo"] },
  { date: "03 Οκτ 2023", year: 2023, type: "Ανακοίνωση", title: "Απολογισμός δωρεών και ευχαριστίες προς την τοπική κοινότητα", attachments: ["pdf"] },
  { date: "20 Ιουν 2021", year: 2021, type: "Νέα", title: "Νέα συνεργασία για την υποστήριξη των αναγκών του Ασύλου", attachments: ["photo"] },
  { date: "16 Δεκ 2019", year: 2019, type: "Εκδήλωση", title: "Γιορτινό παζάρι ενίσχυσης του Ασύλου", attachments: ["photo", "pdf"] },
  { date: "30 Μαρ 2017", year: 2017, type: "Ανακοίνωση", title: "Πρόσκληση ενδιαφέροντος για προμήθειες", attachments: ["pdf"] },
  { date: "12 Νοε 2014", year: 2014, type: "Νέα", title: "Οι άνθρωποι της Πάτρας δίπλα στο Άσυλο", attachments: ["photo"] }
];
const newsList = document.querySelector("#news-list"); const resultCount = document.querySelector("#result-count"); const searchInput = document.querySelector("#news-search"); const yearFilter = document.querySelector("#year-filter"); const typeFilter = document.querySelector("#type-filter"); const loadMoreButton = document.querySelector("#load-more"); const dialog = document.querySelector("#attachment-dialog"); let visibleItems = 6;
function filterItems() { const query = searchInput.value.trim().toLocaleLowerCase("el"); return announcements.filter((item) => item.title.toLocaleLowerCase("el").includes(query) && (yearFilter.value === "all" || String(item.year) === yearFilter.value) && (typeFilter.value === "all" || item.type === typeFilter.value)); }
function renderArchive() { const items = filterItems(); resultCount.textContent = `${items.length} ${items.length === 1 ? "αποτέλεσμα" : "αποτελέσματα"}`; newsList.innerHTML = items.slice(0, visibleItems).map((item) => `<article class="news-card"><div class="news-meta"><span class="tag">${item.type}</span><time>${item.date}</time></div><h3>${item.title}</h3><div class="attachments">${item.attachments.map((attachment) => `<button class="attachment" type="button" data-index="${announcements.indexOf(item)}" data-attachment="${attachment}">${attachment === "pdf" ? "Έγγραφο PDF" : "Φωτογραφίες"}</button>`).join("")}</div></article>`).join("") || "<p class=\"empty-results\">Δεν βρέθηκαν ανακοινώσεις με αυτά τα κριτήρια.</p>"; loadMoreButton.hidden = items.length <= visibleItems; }
[...new Set(announcements.map((item) => item.year))].sort((a, b) => b - a).forEach((year) => yearFilter.insertAdjacentHTML("beforeend", `<option value="${year}">${year}</option>`));
[searchInput, yearFilter, typeFilter].forEach((control) => control.addEventListener("input", () => { visibleItems = 6; renderArchive(); })); document.querySelector("#clear-filters").addEventListener("click", () => { searchInput.value = ""; yearFilter.value = "all"; typeFilter.value = "all"; visibleItems = 6; renderArchive(); }); loadMoreButton.addEventListener("click", () => { visibleItems += 6; renderArchive(); }); newsList.addEventListener("click", (event) => { const button = event.target.closest(".attachment"); if (!button) return; const item = announcements[button.dataset.index]; const label = button.dataset.attachment === "pdf" ? "Έγγραφο" : "Φωτογραφικό αρχείο"; document.querySelector("#dialog-content").innerHTML = `<p class="eyebrow">${label}</p><h2>${item.title}</h2><p>Στην τελική έκδοση, εδώ θα ανοίγει το αυθεντικό αρχείο ή η συλλογή φωτογραφιών της ανάρτησης.</p>`; dialog.showModal(); }); document.querySelector(".dialog-close").addEventListener("click", () => dialog.close()); dialog.addEventListener("click", (event) => { if (event.target === dialog) dialog.close(); }); renderArchive();
